export const sampleKanji = [
  {
    id: 1,
    character: '田',
    readings: { on: 'デン', kun: 'た' },
    meaning: 'rice field, rice paddy',
    strokes: 5,
    jlptLevel: 'N4',
    frequency: 'Common',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 2,
    character: '方',
    readings: { on: 'ホウ', kun: 'かた、がた' },
    meaning: 'direction, person, alternative',
    strokes: 4,
    jlptLevel: 'N4',
    frequency: 'Common',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 3,
    character: '多',
    readings: { on: 'タ', kun: 'おお.い、まさ.に、まさ.る' },
    meaning: 'many, frequent, much',
    strokes: 6,
    jlptLevel: 'N4',
    frequency: 'Common',
    isFavorite: true,
    grade: 'grade 2'
  },
  {
    id: 4,
    character: '形',
    readings: { on: 'ケイ、ギョウ', kun: 'かた、かたち、なり' },
    meaning: 'shape, form, style',
    strokes: 7,
    jlptLevel: 'N4',
    frequency: 'Common',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 5,
    character: '他',
    readings: { on: 'タ', kun: 'ほか' },
    meaning: 'other, another, the others',
    strokes: 5,
    jlptLevel: 'N4',
    frequency: 'Common',
    isFavorite: false,
    grade: 'grade 3'
  },
  {
    id: 6,
    character: '太',
    readings: { on: 'タイ、タ', kun: 'ふと.い、ふと.る' },
    meaning: 'plump, thick, big around',
    strokes: 4,
    jlptLevel: 'N1',
    frequency: 'Common',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 7,
    character: '潟',
    readings: { on: 'セキ', kun: 'かた' },
    meaning: 'lagoon',
    strokes: 15,
    jlptLevel: 'N1',
    frequency: 'Uncommon',
    isFavorite: false,
    grade: 'grade 4'
  },
  {
    id: 8,
    character: '水',
    readings: { on: 'スイ', kun: 'みず' },
    meaning: 'water',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 9,
    character: '火',
    readings: { on: 'カ', kun: 'ひ' },
    meaning: 'fire',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: true,
    grade: 'grade 1'
  },
  {
    id: 10,
    character: '木',
    readings: { on: 'モク・ボク', kun: 'き' },
    meaning: 'tree, wood',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 11,
    character: '金',
    readings: { on: 'キン・コン', kun: 'かね' },
    meaning: 'gold, money',
    strokes: 8,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 12,
    character: '土',
    readings: { on: 'ド・ト', kun: 'つち' },
    meaning: 'earth, soil',
    strokes: 3,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 13,
    character: '日',
    readings: { on: 'ニチ・ジツ', kun: 'ひ・か' },
    meaning: 'sun, day',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 14,
    character: '月',
    readings: { on: 'ゲツ・ガツ', kun: 'つき' },
    meaning: 'moon, month',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 15,
    character: '人',
    readings: { on: 'ジン・ニン', kun: 'ひと' },
    meaning: 'person',
    strokes: 2,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 16,
    character: '大',
    readings: { on: 'ダイ・タイ', kun: 'おお・だい' },
    meaning: 'big, large',
    strokes: 3,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 17,
    character: '小',
    readings: { on: 'ショウ', kun: 'ちい・こ・お' },
    meaning: 'small, little',
    strokes: 3,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: true,
    grade: 'grade 1'
  },
  {
    id: 18,
    character: '学',
    readings: { on: 'ガク', kun: 'まな(ぶ)' },
    meaning: 'study, learn',
    strokes: 8,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 19,
    character: '校',
    readings: { on: 'コウ', kun: '' },
    meaning: 'school',
    strokes: 10,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 20,
    character: '本',
    readings: { on: 'ホン', kun: 'もと' },
    meaning: 'book, origin',
    strokes: 5,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 21,
    character: '中',
    readings: { on: 'チュウ', kun: 'なか' },
    meaning: 'middle, center',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 22,
    character: '年',
    readings: { on: 'ネン', kun: 'とし' },
    meaning: 'year',
    strokes: 6,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 23,
    character: '時',
    readings: { on: 'ジ', kun: 'とき・じ' },
    meaning: 'time, hour',
    strokes: 10,
    jlptLevel: 'N4',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 24,
    character: '間',
    readings: { on: 'カン・ケン', kun: 'あいだ・ま' },
    meaning: 'interval, space',
    strokes: 12,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 25,
    character: '分',
    readings: { on: 'ブン・フン', kun: 'わ(ける)' },
    meaning: 'minute, divide',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 26,
    character: '今',
    readings: { on: 'コン・キン', kun: 'いま' },
    meaning: 'now',
    strokes: 4,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 27,
    character: '何',
    readings: { on: 'カ', kun: 'なに・なん' },
    meaning: 'what',
    strokes: 7,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 28,
    character: '行',
    readings: { on: 'コウ・ギョウ', kun: 'い(く)・ゆ(く)' },
    meaning: 'go, line',
    strokes: 6,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 29,
    character: '来',
    readings: { on: 'ライ', kun: 'く(る)' },
    meaning: 'come',
    strokes: 7,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 30,
    character: '見',
    readings: { on: 'ケン', kun: 'み(る)' },
    meaning: 'see, look',
    strokes: 7,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 31,
    character: '言',
    readings: { on: 'ゲン・ゴン', kun: 'い(う)・こと' },
    meaning: 'say, word',
    strokes: 7,
    jlptLevel: 'N3',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 32,
    character: '話',
    readings: { on: 'ワ', kun: 'はな(す)' },
    meaning: 'talk, speak',
    strokes: 13,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 33,
    character: '聞',
    readings: { on: 'ブン・モン', kun: 'き(く)' },
    meaning: 'hear, ask',
    strokes: 14,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 34,
    character: '読',
    readings: { on: 'ドク・トク', kun: 'よ(む)' },
    meaning: 'read',
    strokes: 14,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 35,
    character: '書',
    readings: { on: 'ショ', kun: 'か(く)' },
    meaning: 'write',
    strokes: 10,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 36,
    character: '食',
    readings: { on: 'ショク', kun: 'た(べる)' },
    meaning: 'eat, food',
    strokes: 9,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 37,
    character: '飲',
    readings: { on: 'イン', kun: 'の(む)' },
    meaning: 'drink',
    strokes: 12,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 3'
  },
  {
    id: 38,
    character: '作',
    readings: { on: 'サク・サ', kun: 'つく(る)' },
    meaning: 'make, create',
    strokes: 7,
    jlptLevel: 'N4',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 39,
    character: '買',
    readings: { on: 'バイ', kun: 'か(う)' },
    meaning: 'buy',
    strokes: 12,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 40,
    character: '売',
    readings: { on: 'バイ', kun: 'う(る)' },
    meaning: 'sell',
    strokes: 7,
    jlptLevel: 'N4',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 41,
    character: '車',
    readings: { on: 'シャ', kun: 'くるま' },
    meaning: 'car, vehicle',
    strokes: 7,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 42,
    character: '電',
    readings: { on: 'デン', kun: '' },
    meaning: 'electricity',
    strokes: 13,
    jlptLevel: 'N4',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 43,
    character: '駅',
    readings: { on: 'エキ', kun: '' },
    meaning: 'station',
    strokes: 14,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 3'
  },
  {
    id: 44,
    character: '道',
    readings: { on: 'ドウ・トウ', kun: 'みち' },
    meaning: 'road, way',
    strokes: 12,
    jlptLevel: 'N4',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 45,
    character: '家',
    readings: { on: 'カ・ケ', kun: 'いえ・うち' },
    meaning: 'house, home',
    strokes: 10,
    jlptLevel: 'N4',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 46,
    character: '部',
    readings: { on: 'ブ', kun: '' },
    meaning: 'part, section',
    strokes: 11,
    jlptLevel: 'N4',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 3'
  },
  {
    id: 47,
    character: '屋',
    readings: { on: 'オク', kun: 'や' },
    meaning: 'roof, shop',
    strokes: 9,
    jlptLevel: 'N4',
    frequency: 'Common',
    isFavorite: false,
    grade: 'grade 3'
  },
  {
    id: 48,
    character: '店',
    readings: { on: 'テン', kun: 'みせ' },
    meaning: 'shop, store',
    strokes: 8,
    jlptLevel: 'N4',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 49,
    character: '会',
    readings: { on: 'カイ・エ', kun: 'あ(う)' },
    meaning: 'meet, meeting',
    strokes: 6,
    jlptLevel: 'N4',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 50,
    character: '社',
    readings: { on: 'シャ', kun: 'やしろ' },
    meaning: 'company, society',
    strokes: 7,
    jlptLevel: 'N4',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 51,
    character: '名',
    readings: { on: 'メイ・ミョウ', kun: 'な' },
    meaning: 'name',
    strokes: 6,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 52,
    character: '前',
    readings: { on: 'ゼン', kun: 'まえ' },
    meaning: 'front, before',
    strokes: 9,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 53,
    character: '後',
    readings: { on: 'ゴ・コウ', kun: 'うし(ろ)・あと' },
    meaning: 'behind, after',
    strokes: 9,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 54,
    character: '上',
    readings: { on: 'ジョウ・ショウ', kun: 'うえ・あ(がる)' },
    meaning: 'up, above',
    strokes: 3,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 55,
    character: '下',
    readings: { on: 'カ・ゲ', kun: 'した・さ(がる)' },
    meaning: 'down, below',
    strokes: 3,
    jlptLevel: 'N5',
    frequency: 'Very High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 56,
    character: '左',
    readings: { on: 'サ', kun: 'ひだり' },
    meaning: 'left',
    strokes: 5,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 57,
    character: '右',
    readings: { on: 'ウ・ユウ', kun: 'みぎ' },
    meaning: 'right',
    strokes: 5,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 1'
  },
  {
    id: 58,
    character: '東',
    readings: { on: 'トウ', kun: 'ひがし' },
    meaning: 'east',
    strokes: 8,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 59,
    character: '西',
    readings: { on: 'セイ・サイ', kun: 'にし' },
    meaning: 'west',
    strokes: 6,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  },
  {
    id: 60,
    character: '南',
    readings: { on: 'ナン', kun: 'みなみ' },
    meaning: 'south',
    strokes: 9,
    jlptLevel: 'N5',
    frequency: 'High',
    isFavorite: false,
    grade: 'grade 2'
  }
];

export const jlptColors = {
  N5: '#4caf50',
  N4: '#8bc34a', 
  N3: '#ff9800',
  N2: '#ff5722',
  N1: '#f44336'
};

export const SORT_OPTIONS = [
  { value: 'strokes', label: 'Stroke Count' },
  { value: 'jlpt', label: 'JLPT Level' },
  { value: 'frequency', label: 'Frequency' },
  { value: 'alphabetical', label: 'Alphabetical' }
];